/// A class containing constants used in the application.
class Constants {
 /// The base URL for the Petfinder API.
 static const String petfinderUrl = "https://api.petfinder.com/v2/";

 /// The authentication token for accessing the Petfinder API.
 static const String token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ5TThvTERXVEpOOGdraEdLZzRHN0lHQjZ5ekFRU3pxSE1PSUJiTHJwWFhac05KTkVicyIsImp0aSI6IjU4N2JjYTAxN2I3ZTdhYTU5ZGU1ODBhZDg4YTVjZWExNTc2NjhiMTk3N2YzM2RjNjJmN2I2OTc0NGY5ZDRkNGY5ODZmZmM5ZmMzMjNmNmVhIiwiaWF0IjoxNzEzNDQzMDgxLCJuYmYiOjE3MTM0NDMwODEsImV4cCI6MTcxMzQ0NjY4MSwic3ViIjoiIiwic2NvcGVzIjpbXX0.pxpAB1swIhZcTfvsCCtlNR0M8WVNYNeVPUS6xDqj3l-rpjxdPwzhZxWVRi1CimPlbSzr_KT3xdBNfKLoydxEq-7dAk_qHyftQVZrxK9UVSqtWSrv9CA-fXqmZr1iDT8tlVysEi0DCsb89pLEfvtg-rGYVnPwgJ0Fl52zhRVnBd0nXDEvnW9JmVSXUmYfHGdsvbEghVffCpK6wqxKa9ZtviqvgGG5d-wyofCILw9fTyWruFTO5AUp65Llgj0kOzxZQrzL-mzuVu2YoGeckX93FDBn_UtjHPO1eUaP-7bUckh_s4J_hHrGGnkGJmnwCPMhAR58mBLoSz-f2iJsKyqdGA";
}